[package]
name = "deadbeef-core"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[dependencies]
hex = "0.4"
hex-literal = "0.4"
rand = { version = "0.8", features = ["small_rng"] }
tiny-keccak = { version = "2", features = ["keccak"] }
